GET http://localhost:8080/

### CSRF TOKEN
# @name cli_route
# csrf token for secure form submission
# GET http://localhost:8080/cli/ccwc

### HEALTH
# @name api_route
# csrf token for secure form submission
GET http://localhost:8080/api/health

###
# 5a74ba70c77bbdf7272b134de41dd640
GET http://localhost:8080/api/mailchimp/newsletter_list/members/6c54666c8cf69dcc9e1e00962298451f?skipMergeValidation=true&excludeFields=email_address,password,merge_fields
Content-Type: application/json

###
GET http://localhost:8080/api/mailchimp/newsletter_list/members?count=2

###
POST http://localhost:8080/api/mailchimp/newsletter_list/members/subscribe
Content-Type: application/json

{
    "email_address": "Ebony_Brekke@gmail.com",
    "status": "pending"
}

###
GET http://localhost:8080/api/mailchimp/newsletter_list/members/Ebony_Brekke@gmail.com