GET http://localhost:8080/

### CSRF TOKEN
# @name cli_route
# csrf token for secure form submission
# GET http://localhost:8080/cli/ccwc

### HEALTH
# @name api_route
# csrf token for secure form submission
GET http://localhost:8080/api/health

###
GET http://localhost:8080/api/mailchimp/newsletter_list/members
Content-Type: application/json

###
POST http://localhost:8080/api/mailchimp/newsletter_list/members/subscribe
Content-Type: application/json

{
    "email_address": "Ebony_Brekke@gmail.com",
    "status": "pending"
}

###
GET http://localhost:8080/api/mailchimp/newsletter_list/members/Ebony_Brekke@gmail.com